import type { PanelDefinition } from "@/lib/panels/types";

export const PANEL_REGISTRY: PanelDefinition[] = [
  {
    key: "event-timeline",
    title: "Threat Timeline",
    category: "crisis",
    componentId: "event-timeline",
    defaultSize: { w: 4, h: 5 },
    minSize: { w: 3, h: 3 },
    dataDependencies: ["gdelt-doc", "reliefweb", "ucdp", "acled"],
    mobile: "collapsed",
    description: "Cross-source event clusters with corroboration counts",
  },
  {
    key: "globe-map",
    title: "Global Map",
    category: "map",
    componentId: "globe-map",
    defaultSize: { w: 12, h: 8 },
    minSize: { w: 6, h: 4 },
    dataDependencies: ["opensky", "usgs-earthquakes", "cctv-agencies", "celestrak"],
    supportedLayers: ["flights", "events", "quakes", "cctv", "ships", "iss", "satellites"],
    mobile: "enabled",
    description: "Multi-layer MapLibre globe with live toggles",
  },
  {
    key: "live-news",
    title: "Live News TV",
    category: "news",
    componentId: "live-news",
    defaultSize: { w: 4, h: 5 },
    minSize: { w: 3, h: 4 },
    dataDependencies: ["live-channels"],
    mobile: "collapsed",
    description: "Official public live news streams",
  },
  {
    key: "wire-headlines",
    title: "Wire",
    category: "news",
    componentId: "wire-headlines",
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    dataDependencies: ["gdelt-doc", "reliefweb"],
    mobile: "collapsed",
  },
  {
    key: "markets-snapshot",
    title: "Markets",
    category: "markets",
    componentId: "markets-snapshot",
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    dataDependencies: ["stooq-eod", "coingecko", "world-bank", "fred"],
    mobile: "collapsed",
    description: "EOD equities/crypto with provider delay labels",
  },
  {
    key: "stocks-ticker",
    title: "Stocks Ticker",
    category: "markets",
    componentId: "stocks-ticker",
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    dataDependencies: ["stooq-eod", "coingecko"],
    mobile: "collapsed",
    description: "Live market movers and tickers",
  },
  {
    key: "my-monitors",
    title: "My Monitors",
    category: "system",
    componentId: "my-monitors",
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    dataDependencies: ["alert-engine"],
    mobile: "collapsed",
    description: "Alert rules, recent events, and watchlists",
  },
  {
    key: "cameras",
    title: "Traffic Cameras",
    category: "system",
    componentId: "cameras",
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    dataDependencies: ["cctv-agencies"],
    mobile: "disabled",
  },
  {
    key: "conflict-events",
    title: "Conflict Events",
    category: "crisis",
    componentId: "conflict-events",
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    dataDependencies: ["ucdp", "acled", "gdelt-doc"],
    mobile: "collapsed",
    description: "Armed conflict and escalation feed",
  },
  {
    key: "outbreaks-monitor",
    title: "Outbreaks",
    category: "crisis",
    componentId: "outbreaks-monitor",
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    dataDependencies: ["reliefweb"],
    mobile: "collapsed",
    description: "Health and humanitarian outbreak signals",
  },
  {
    key: "defcon-posture",
    title: "DEFCON Posture",
    category: "crisis",
    componentId: "defcon-posture",
    defaultSize: { w: 3, h: 4 },
    minSize: { w: 3, h: 3 },
    dataDependencies: ["cyber", "conflict", "earth"],
    mobile: "collapsed",
    description: "Composite readiness heuristic from live signals",
  },
  {
    key: "watch-signals",
    title: "Watch Signals",
    category: "crisis",
    componentId: "watch-signals",
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    dataDependencies: ["gdelt-doc", "cyber", "conflict"],
    mobile: "collapsed",
    description: "High-severity leading indicators across modules",
  },
  {
    key: "aviation-status",
    title: "Aviation",
    category: "aviation",
    componentId: "aviation-status",
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    dataDependencies: ["opensky", "faa-nas"],
    mobile: "collapsed",
    description: "ADS-B snapshot and aviation notices",
  },
  {
    key: "maritime-status",
    title: "Maritime",
    category: "maritime",
    componentId: "maritime-status",
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    dataDependencies: ["aishub", "aisstream"],
    mobile: "collapsed",
    description: "Vessel tracking and maritime notices",
  },
  {
    key: "space-tracker",
    title: "Space",
    category: "space",
    componentId: "space-tracker",
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    dataDependencies: ["celestrak", "nasa-firms", "iss"],
    mobile: "collapsed",
    description: "ISS, satellites, space weather",
  },
  {
    key: "cyber-threats",
    title: "Cyber Threats",
    category: "cyber",
    componentId: "cyber-threats",
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    dataDependencies: ["cisa-kev", "nvd"],
    mobile: "collapsed",
    description: "KEV, CVEs, and cyber incident feed",
  },
  {
    key: "provider-health",
    title: "Data Sources",
    category: "system",
    componentId: "provider-health",
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    dataDependencies: [],
    mobile: "disabled",
  },
];

const byKey = new Map(PANEL_REGISTRY.map((p) => [p.key, p]));

export function getPanel(key: string): PanelDefinition | undefined {
  return byKey.get(key);
}

export function listPanels(category?: PanelDefinition["category"]): PanelDefinition[] {
  return category ? PANEL_REGISTRY.filter((p) => p.category === category) : [...PANEL_REGISTRY];
}

export const PANEL_COUNT = PANEL_REGISTRY.length;
