/**
 * Central provider registry — auth class, license, schedule and default enablement.
 * Source of truth aligned with docs/DATA_SOURCES.md and argus_data_source_registry.csv.
 */

import type { ProviderDefinition } from "@/lib/connectors/contracts";

function def(p: ProviderDefinition): ProviderDefinition {
  return p;
}

export const PROVIDER_REGISTRY: ProviderDefinition[] = [
  def({
    id: "usgs-earthquakes",
    domains: ["earth"],
    cost: "open",
    secretClass: "none",
    requiredEnv: [],
    defaultEnabled: true,
    defaultPolicy: "default",
    scheduleSeconds: 300,
    contentPolicy: "metadata_only",
    attribution: "USGS",
    licenseUrl: "https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits",
    docsUrl: "https://earthquake.usgs.gov/earthquakes/feed/",
    coverage: "Global",
    legacyConnectorId: "usgs_earthquakes",
  }),
  def({
    id: "nasa-eonet",
    domains: ["earth"],
    cost: "open",
    secretClass: "none",
    requiredEnv: [],
    defaultEnabled: true,
    defaultPolicy: "default",
    scheduleSeconds: 900,
    contentPolicy: "metadata_only",
    attribution: "NASA EONET",
    licenseUrl: "https://www.nasa.gov/nasa-open-access-agreement/",
    docsUrl: "https://eonet.gsfc.nasa.gov/docs/v3",
    coverage: "Global",
    legacyConnectorId: "nasa_eonet",
  }),
  def({
    id: "nasa-firms",
    domains: ["earth", "conflict"],
    cost: "free-limited",
    secretClass: "server-secret",
    requiredEnv: ["NASA_FIRMS_MAP_KEY"],
    defaultEnabled: false,
    defaultPolicy: "opt-in",
    scheduleSeconds: 600,
    contentPolicy: "metadata_only",
    attribution: "NASA FIRMS",
    licenseUrl: "https://earthdata.nasa.gov/earth-observation-data/data-use-policy",
    docsUrl: "https://firms.modaps.eosdis.nasa.gov/api/",
    coverage: "Global (key required)",
    legacyConnectorId: "nasa-firms",
  }),
  def({
    id: "gdelt-doc",
    domains: ["news", "conflict"],
    cost: "open",
    secretClass: "none",
    requiredEnv: [],
    optionalEnv: ["GDELT_DOC_API_URL", "GDELT_ENABLE"],
    defaultEnabled: true,
    defaultPolicy: "default",
    scheduleSeconds: 600,
    contentPolicy: "excerpt_only",
    attribution: "GDELT Project",
    licenseUrl: "https://www.gdeltproject.org/about.html",
    docsUrl: "https://www.gdeltproject.org/",
    coverage: "Global",
    legacyConnectorId: "gdelt_events",
  }),
  def({
    id: "reliefweb",
    domains: ["news", "conflict"],
    cost: "open",
    secretClass: "none",
    requiredEnv: [],
    defaultEnabled: true,
    defaultPolicy: "default",
    scheduleSeconds: 900,
    contentPolicy: "excerpt_only",
    attribution: "ReliefWeb / OCHA",
    licenseUrl: "https://reliefweb.int/terms-conditions",
    docsUrl: "https://apidoc.reliefweb.int/",
    coverage: "Global",
    legacyConnectorId: "reliefweb_reports",
  }),
  def({
    id: "ucdp",
    domains: ["conflict"],
    cost: "free-limited",
    secretClass: "server-secret",
    requiredEnv: ["UCDP_ACCESS_TOKEN"],
    defaultEnabled: false,
    defaultPolicy: "opt-in",
    scheduleSeconds: 3600,
    contentPolicy: "metadata_only",
    attribution: "UCDP, Uppsala University",
    licenseUrl: "https://ucdp.uu.se/downloads/",
    docsUrl: "https://ucdp.uu.se/apidocs/",
    coverage: "Global",
    legacyConnectorId: "ucdp_events",
  }),
  def({
    id: "acled",
    domains: ["conflict"],
    cost: "free-limited",
    secretClass: "server-secret",
    requiredEnv: ["ACLED_API_KEY", "ACLED_EMAIL"],
    defaultEnabled: false,
    defaultPolicy: "opt-in",
    scheduleSeconds: 3600,
    contentPolicy: "metadata_only",
    attribution: "ACLED",
    licenseUrl: "https://acleddata.com/terms-of-use/",
    docsUrl: "https://developer.acleddata.com/",
    coverage: "Global",
    legacyConnectorId: "acled_events",
  }),
  def({
    id: "opensky",
    domains: ["aviation", "live"],
    cost: "free-limited",
    secretClass: "server-secret",
    requiredEnv: [],
    optionalEnv: ["OPENSKY_CLIENT_ID", "OPENSKY_CLIENT_SECRET"],
    defaultEnabled: true,
    defaultPolicy: "default",
    scheduleSeconds: 90,
    contentPolicy: "metadata_only",
    attribution: "OpenSky Network",
    licenseUrl: "https://opensky-network.org/about/faq",
    docsUrl: "https://openskynetwork.github.io/opensky-api/rest.html",
    coverage: "Global (receiver-dependent, sampled)",
    legacyConnectorId: "opensky_states",
  }),
  def({
    id: "adsb-lol",
    domains: ["aviation", "live"],
    cost: "open",
    secretClass: "none",
    requiredEnv: [],
    defaultEnabled: true,
    defaultPolicy: "fallback",
    scheduleSeconds: 30,
    contentPolicy: "metadata_only",
    attribution: "adsb.lol community",
    licenseUrl: "https://api.adsb.lol/docs",
    docsUrl: "https://api.adsb.lol/docs",
    coverage: "Receiver-dependent",
  }),
  def({
    id: "wingbits",
    domains: ["aviation", "live"],
    cost: "freemium",
    secretClass: "server-secret",
    requiredEnv: ["WINGBITS_API_KEY"],
    defaultEnabled: false,
    defaultPolicy: "off",
    scheduleSeconds: 60,
    contentPolicy: "metadata_only",
    attribution: "Wingbits",
    licenseUrl: "https://wingbits.com/",
    docsUrl: "https://wingbits.com/",
    coverage: "Provider-dependent",
  }),
  def({
    id: "faa-nas",
    domains: ["aviation"],
    cost: "open",
    secretClass: "none",
    requiredEnv: [],
    defaultEnabled: true,
    defaultPolicy: "default",
    scheduleSeconds: 600,
    contentPolicy: "metadata_only",
    attribution: "FAA",
    licenseUrl: "https://www.faa.gov/",
    docsUrl: "https://nasstatus.faa.gov/",
    coverage: "United States",
    legacyConnectorId: "faa_status",
  }),
  def({
    id: "aisstream",
    domains: ["maritime", "live"],
    cost: "free-limited",
    secretClass: "server-secret",
    requiredEnv: ["AISSTREAM_API_KEY"],
    defaultEnabled: false,
    defaultPolicy: "opt-in",
    scheduleSeconds: 120,
    contentPolicy: "metadata_only",
    attribution: "AISStream",
    licenseUrl: "https://aisstream.io/documentation",
    docsUrl: "https://aisstream.io/documentation",
    coverage: "Global (receiver-dependent)",
  }),
  def({
    id: "aishub",
    domains: ["maritime", "live"],
    cost: "free-limited",
    secretClass: "server-secret",
    requiredEnv: ["AISHUB_API_KEY"],
    defaultEnabled: false,
    defaultPolicy: "opt-in",
    scheduleSeconds: 120,
    contentPolicy: "metadata_only",
    attribution: "AISHub",
    licenseUrl: "https://www.aishub.net/",
    docsUrl: "https://www.aishub.net/",
    coverage: "Limited bbox (English Channel default)",
    legacyConnectorId: "aishub_vessels",
  }),
  def({
    id: "celestrak",
    domains: ["space"],
    cost: "open",
    secretClass: "none",
    requiredEnv: [],
    defaultEnabled: true,
    defaultPolicy: "default",
    scheduleSeconds: 7200,
    contentPolicy: "full_cache",
    attribution: "CelesTrak",
    licenseUrl: "https://celestrak.org/",
    docsUrl: "https://celestrak.org/NORAD/documentation/gp-data-formats.php",
    coverage: "Global catalog",
    legacyConnectorId: "celestrak_recent",
  }),
  def({
    id: "cctv-agencies",
    domains: ["live", "infrastructure"],
    cost: "open",
    secretClass: "server-secret",
    requiredEnv: [],
    optionalEnv: [
      "CCTV_ENABLE_TFL", "CCTV_ENABLE_WSDOT", "CCTV_ENABLE_CALTRANS",
      "CCTV_ENABLE_NYCDOT", "CCTV_ENABLE_VICROADS", "TFL_APP_KEY",
      "WSDOT_ACCESS_CODE", "NYC_511_API_KEY", "VICROADS_CAMERAS_URL",
    ],
    defaultEnabled: true,
    defaultPolicy: "default",
    scheduleSeconds: 300,
    contentPolicy: "metadata_only",
    attribution: "TfL / WSDOT / Caltrans / NYC / VicRoads",
    licenseUrl: "Agency-specific open-data terms",
    docsUrl: "https://api.tfl.gov.uk/",
    coverage: "Regional (London, US states, NYC, Victoria AU)",
  }),
  def({
    id: "nvd",
    domains: ["cyber"],
    cost: "open",
    secretClass: "server-secret",
    requiredEnv: [],
    optionalEnv: ["NVD_API_KEY"],
    defaultEnabled: true,
    defaultPolicy: "default",
    scheduleSeconds: 1800,
    contentPolicy: "metadata_only",
    attribution: "NIST NVD",
    licenseUrl: "https://nvd.nist.gov/general/legal-disclaimer",
    docsUrl: "https://nvd.nist.gov/developers/vulnerabilities",
    coverage: "Global CVE",
    legacyConnectorId: "nvd_cves",
  }),
  def({
    id: "world-bank",
    domains: ["macro"],
    cost: "open",
    secretClass: "none",
    requiredEnv: [],
    defaultEnabled: true,
    defaultPolicy: "default",
    scheduleSeconds: 86400,
    contentPolicy: "metadata_only",
    attribution: "World Bank",
    licenseUrl: "https://www.worldbank.org/en/about/legal/terms-of-use-for-datasets",
    docsUrl: "https://datahelpdesk.worldbank.org/",
    coverage: "Global",
    legacyConnectorId: "worldbank_indicators",
  }),
  def({
    id: "fred",
    domains: ["macro", "markets"],
    cost: "free-limited",
    secretClass: "server-secret",
    requiredEnv: ["FRED_API_KEY"],
    defaultEnabled: false,
    defaultPolicy: "opt-in",
    scheduleSeconds: 3600,
    contentPolicy: "metadata_only",
    attribution: "FRED / St. Louis Fed",
    licenseUrl: "https://fred.stlouisfed.org/legal/",
    docsUrl: "https://fred.stlouisfed.org/docs/api/fred/",
    coverage: "US / global series",
    legacyConnectorId: "fred_series",
  }),
  def({
    id: "yahoo-finance",
    domains: ["markets"],
    cost: "open",
    secretClass: "none",
    requiredEnv: [],
    defaultEnabled: false,
    defaultPolicy: "off",
    scheduleSeconds: 300,
    contentPolicy: "metadata_only",
    attribution: "Yahoo (unofficial)",
    licenseUrl: "Undocumented — not for production",
    docsUrl: "Undocumented",
    coverage: "Selected symbols",
    legacyConnectorId: "yahoo_quotes",
  }),
];

const byId = new Map(PROVIDER_REGISTRY.map((p) => [p.id, p]));

export function getProvider(id: string): ProviderDefinition | undefined {
  return byId.get(id);
}

export function listProviders(filter?: { domain?: string; enabledOnly?: boolean }): ProviderDefinition[] {
  return PROVIDER_REGISTRY.filter((p) => {
    if (filter?.domain && !p.domains.includes(filter.domain)) return false;
    if (filter?.enabledOnly && !isProviderEnvEnabled(p)) return false;
    return true;
  });
}

export function isProviderEnvEnabled(provider: ProviderDefinition): boolean {
  if (provider.defaultPolicy === "off") return false;
  const missing = provider.requiredEnv.filter((k) => !process.env[k]?.trim());
  if (missing.length > 0) return provider.defaultPolicy === "default" && provider.requiredEnv.length === 0;
  return provider.defaultEnabled;
}

export function providerEnvStatus(provider: ProviderDefinition): {
  configured: boolean;
  missingEnv: string[];
} {
  const missingEnv = provider.requiredEnv.filter((k) => !process.env[k]?.trim());
  return { configured: missingEnv.length === 0, missingEnv };
}
